spring:
  application:
    name: readRent
  
  datasource:
    url: jdbc:mysql://localhost:3306/rentRead
    username: root
    password: Abcdef@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true 
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    
